Areas/Admin/Controllers/AdminProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PagedList.Core;
using PE.Models;
using PE.Models.paging;
using PE.Helpers;
using System.IO;
using AspNetCoreHero.ToastNotification.Abstractions;

namespace PE.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class AdminProductsController : Controller
    {
        private readonly shopPEContext _context;

        public INotyfService _notyfService { get; }

        public AdminProductsController(shopPEContext context, INotyfService notyfService)
        {
            _context = context;
            _notyfService = notyfService;
        }

        // GET: Admin/AdminProducts
        public async Task<IActionResult> Index(string sortOrder, string searchString, string searchCate, string currentFilter, int? pageNumber)
        {

            /////filter
            ViewData["NameSortParm"] = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewData["Category"] = String.IsNullOrEmpty(sortOrder) ? "Cat_desc" : "";
            ViewData["Status"] = String.IsNullOrEmpty(sortOrder) ? "Status" : "";
            ViewData["Price"] = String.IsNullOrEmpty(sortOrder) ? "Price_desc" : "";
            ViewData["CurrentSort"] = sortOrder;

            //paging
            if (searchString != null)
            {
                pageNumber = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewData["CurrentFilter"] = searchString;

            ////
            var products = from s in _context.Products
                           select s;

            //search
            //name
            if (!String.IsNullOrEmpty(searchString))
            {
                products = products.Where(p => p.ProductName.Contains(searchString));
            }

            //category
            if (!String.IsNullOrEmpty(searchCate))
            {
                products = products.Where(p => p.Cat.CatName.Contains(searchCate));
            }
            //sort
            switch (sortOrder)
            {
                case "name_desc":
                    products = products.OrderByDescending(s => s.ProductName);
                    break;
                case "Cat_desc":
                    products = products.OrderByDescending(s => s.Cat.CatName);
                    break;
                case "Price_desc":
                    products = products.OrderByDescending(s => s.Price);
                    break;
                case "Status":
                    products = products.OrderBy(s => s.Active);
                    break;
                default:
                    products = products.OrderBy(s => s.ProductId);
                    break;
            }

            int pageSize = Utilites.PAGE_SIZE;

            //result
            return View(await PaginatedList<Product>.CreateAsync(products.AsNoTracking().Include(c => c.Cat), pageNumber ?? 1, pageSize));

        }

        // GET: Admin/AdminProducts/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Products
                .Include(p => p.Cat)
                .FirstOrDefaultAsync(m => m.ProductId == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // GET: Admin/AdminProducts/Create
        public IActionResult Create()
        {
            ViewData["CatId"] = new SelectList(_context.Categories, "CatId", "CatName");
            return View();
        }

        // POST: Admin/AdminProducts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ProductId,ProductName,ShortDesc,Description,CatId,Price,Discount,Thumb,Video,DateCreated,DateModified,BestSellers,HomeFlag,Active,Tags,Title,Alias,MetaDesc,MetalKey,UnitInStock")] Product product, Microsoft.AspNetCore.Http.IFormFile fThumb)
        {
            if (ModelState.IsValid)
            {
                product.ProductName = Utilites.ToTitleCase(product.ProductName);
                if(fThumb != null)
                {
                    string extentions = Path.GetExtension(fThumb.FileName);
                    string image = Utilites.SEOUrl(product.ProductName) + extentions;
                    product.Thumb = await Utilites.UploadFile(fThumb, @"products", image.ToLower());
                }
                if (string.IsNullOrEmpty(product.Thumb)) product.Thumb = "default.jpg";
                product.Alias = Utilites.SEOUrl(product.ProductName);
                product.DateCreated = DateTime.Now;
                product.DateModified = DateTime.Now;

                _context.Add(product);
                await _context.SaveChangesAsync();
                _notyfService.Success("Success");
                return RedirectToAction(nameof(Index));
            }
            ViewData["CatId"] = new SelectList(_context.Categories, "CatId", "CatName", product.CatId);
            return View(product);
        }

        // GET: Admin/AdminProducts/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Products.FindAsync(id);
            if (product == null)
            {
                return NotFound();
            }
            ViewData["CatId"] = new SelectList(_context.Categories, "CatId", "CatName", product.CatId);
            return View(product);
        }

        // POST: Admin/AdminProducts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ProductId,ProductName,ShortDesc,Description,CatId,Price,Discount,Thumb,Video,DateCreated,DateModified,BestSellers,HomeFlag,Active,Tags,Title,Alias,MetaDesc,MetalKey,UnitInStock")] Product product, Microsoft.AspNetCore.Http.IFormFile fThumb)
        {
            if (id != product.ProductId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    product.ProductName = Utilites.ToTitleCase(product.ProductName);
                    if (fThumb != null)
                    {
                        string extentions = Path.GetExtension(fThumb.FileName);
                        string image = Utilites.SEOUrl(product.ProductName) + extentions;
                        product.Thumb = await Utilites.UploadFile(fThumb, @"products", image.ToLower());
                    }
                    if (string.IsNullOrEmpty(product.Thumb)) product.Thumb = "default.jpg";
                    product.Alias = Utilites.SEOUrl(product.ProductName);
                    product.DateModified = DateTime.Now;

                    _context.Update(product);
                    _notyfService.Success("Success");
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProductExists(product.ProductId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CatId"] = new SelectList(_context.Categories, "CatId", "CatName", product.CatId);
            return View(product);
        }

        // GET: Admin/AdminProducts/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Products
                .Include(p => p.Cat)
                .FirstOrDefaultAsync(m => m.ProductId == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // POST: Admin/AdminProducts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var product = await _context.Products.FindAsync(id);
            _context.Products.Remove(product);
            await _context.SaveChangesAsync();
            _notyfService.Success("Success");
            return RedirectToAction(nameof(Index));
        }

        private bool ProductExists(int id)
        {
            return _context.Products.Any(e => e.ProductId == id);
        }


    }
}

Areas/Admin/Views/AdminProducts/Create.cshtml
@model PE.Models.Product

@{
    ViewData["Title"] = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}
<head>
    <!-- Favicon -->
    <link rel="shortcut icon" href="~/Admin/assets/images/logo/favicon.png">

    <!-- page css -->
    <link href="~/Admin/assets/vendors/select2/select2.css" rel="stylesheet">

    <!-- Core css -->
    <link href="~/Admin/assets/css/app.min.css" rel="stylesheet">
</head>

<h1>Create</h1>
<div class="page-header">
    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a asp-area="Admin" asp-controller="Home" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Home</a>
            <a asp-area="Admin" asp-controller="AdminProducts" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Product list</a>
            <span class="breadcrumb-item active">Create</span>
        </nav>
    </div>
</div>

<h4>Product</h4>
<hr />
<form asp-controller="AdminProducts" asp-action="Create" method="post" enctype="multipart/form-data">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="page-header no-gutters has-tab">
        <div class="d-md-flex m-b-15 align-items-center justify-content-between">
            <div class="media align-items-center m-b-15">
            </div>
            <div class="m-b-15">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </div>
        <ul class="nav nav-tabs">
            <li class="nav-item">
                <a class="nav-link active" data-toggle="tab" href="#product-edit-basic">Basic Info</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" data-toggle="tab" href="#product-edit-option">Option Info</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" data-toggle="tab" href="#product-edit-description">Description</a>
            </li>
        </ul>
    </div>
    <div class="tab-content m-t-15">
        <div class="tab-pane fade show active" id="product-edit-basic">
            <div class="card">
                <div class="card-body">
                    <div class="row">
                        <div class="form-group col-md-9">
                            <label class="font-weight-semibold" asp-for="ProductName">Product Name</label>
                            <input asp-for="ProductName" class="form-control" />
                            <span asp-validation-for="ProductName" class="text-danger"></span>
                        </div>
                        <div class="form-group  col-md-3">
                            <label class="font-weight-semibold" asp-for="UnitInStock">UnitInStock</label>
                            <input asp-for="UnitInStock" class="form-control" />
                            <span asp-validation-for="UnitInStock" class="text-danger"></span>
                        </div>
                    </div>

                    <div class="row">
                        <div class="form-group col-md-6">
                            <label class="font-weight-semibold" asp-for="Price">Price</label>
                            <input asp-for="Price" class="form-control" />
                            <span asp-validation-for="Price" class="text-danger"></span>
                        </div>
                        <div class="form-group  col-md-6">
                            <label class="font-weight-semibold" asp-for="Discount">Discount(%)</label>
                            <input asp-for="Discount" class="form-control" />
                            <span asp-validation-for="Discount" class="text-danger"></span>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="font-weight-semibold" asp-for="Cat">Category</label>
                        <select class="custom-select" asp-for="CatId" style="min-width: 200px" asp-items="ViewBag.CatId">
                            <option value="" disable selected>Select category</option>

                        </select>
                    </div>
                    <div class="form-group">
                        <label class="font-weight-semibold" asp-for="Thumb">Thumbnail</label>
                        <input name="fThumb" asp-for="Thumb" type="file" class="form-control-file" />
                    </div>
                    <div class="row">
                        <div class="m-t-25">
                            <div class="form-group d-flex align-items-center">
                                <div class="switch m-r-10">
                                    <input type="checkbox" asp-for="Active" />
                                    <label for="Active"></label>
                                </div>
                                <label>Active</label>
                            </div>
                            <div class="form-group d-flex align-items-center">
                                <div class="switch m-r-10">
                                    <input type="checkbox" asp-for="HomeFlag" />
                                    <label for="HomeFlag"></label>
                                </div>
                                <label>Home flag</label>
                            </div>
                            <div class="form-group d-flex align-items-center">
                                <div class="switch m-r-10">
                                    <input type="checkbox" asp-for="BestSellers" />
                                    <label for="BestSellers"></label>
                                </div>
                                <label>Best seller</label>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="font-weight-semibold" for="productStatus">Status</label>
                        <select class="custom-select" id="productStatus">
                            <option value="inStock" selected>In Stock</option>
                            <option value="outOfStock">Out of Stock</option>
                            <option value="pending">Pending</option>
                        </select>
                    </div>
                </div>
            </div>
        </div>
        <div class="tab-pane fade" id="product-edit-option">
            <div class="card">
                <div class="card-body">
                    <div class="form-group">
                        <label class="font-weight-semibold" asp-for="Title">Title</label>
                        <input asp-for="Title" class="form-control" />
                        <span asp-validation-for="Title" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label class="font-weight-semibold" asp-for="MetaDesc">MetaDesc</label>
                        <input asp-for="MetaDesc" class="form-control" />
                        <span asp-validation-for="MetaDesc" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label class="font-weight-semibold" asp-for="MetalKey">MetalKey</label>
                        <input asp-for="MetalKey" class="form-control" />
                        <span asp-validation-for="MetalKey" class="text-danger"></span>
                    </div>

                </div>
            </div>
        </div>
        <div class="tab-pane fade" id="product-edit-description">
            <div class="card">
                <div class="card-body">
                    <div class="form-group ">
                        <label class="font-weight-semibold" asp-for="ShortDesc">Short Description</label>
                        <input asp-for="ShortDesc" class="form-control" />
                        <span asp-validation-for="ShortDesc" class="text-danger"></span>
                    </div>
                    <div class="form-group ">
                        <label class="font-weight-semibold" asp-for="Description">Description</label>
                        <input asp-for="Description" class="form-control" />
                        <span asp-validation-for="Description" class="text-danger"></span>
                    </div>
                    @*<div id="productDescription">
                    <label class="font-weight-semibold" asp-for="Description">Description</label>
                    <input asp-for="Description" class="form-control" />
                    <span asp-validation-for="Description" class="text-danger"></span>
                    </div>*@
                </div>
            </div>
        </div>
    </div>
</form>


<!-- Core Vendors JS -->
<script src="~/Admin/assets/js/vendors.min.js"></script>

@section Scripts{
    <script>
        new Quill('#productDescription', {
            theme: 'snow'
        })
    </script>

    <script src="~/Admin/assets/vendors/select2/select2.min.js"></script>
    <script src="~/Admin/assets/vendors/quill/quill.min.js"></script>
    <script src="~/Admin/assets/js/pages/e-commerce-product-edit.js"></script>

}
    <!-- page js -->
    <!-- Core JS -->
    <script src="~/Admin/assets/js/app.min.js"></script>

Areas/Admin/Views/AdminProducts/Delete.cshtml
@model PE.Models.Product

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h1>Delete</h1>
<div class="page-header">
    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a asp-area="Admin" asp-controller="Home" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Home</a>
            <a asp-area="Admin" asp-controller="AdminProducts" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Product list</a>
            <span class="breadcrumb-item active">Delete</span>
        </nav>
        </di

        <h3>Are you sure you want to delete this?</h3>
        <div>
            <h4>Product</h4>
            <hr />
            <div class="row">
                <!-- Column -->
                <div class="col-lg-4 col-xlg-3 col-md-12">
                    <div class="white-box">
                        <div class="user-bg">
                            <img width="max" height="max" alt="user" src="~/images/products/@Model.Thumb">

                        </div>
                        <div class="user-btm-box mt-5 d-md-flex">
                            <div class="col-md-4 col-sm-4 text-center">
                                <h1>
                                    @if (@Model.Thumb != null)
                                    {
                                        <p>@Model.Thumb</p>
                                    }
                                    else
                                    {
                                        <p>Unknown</p>
                                    }
                                </h1>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- Column -->
                <!-- Column -->
                <div class="col-lg-8 col-xlg-9 col-md-12">
                    <div class="card">
                        <div class="card-body">
                            <div class="form-group mb-4">
                                <label class="col-md-12 p-0">Full Name</label>
                                <div class="col-md-12 border-bottom p-0">
                                    <p>@Model.ProductName</p>
                                </div>
                                <div class="form-group mb-4">
                                    <label class="col-md-12 p-0">Title</label>
                                    <div class="col-md-12 border-bottom p-0">
                                        <p>@Model.Title</p>
                                    </div>
                                </div>
                                <div class="form-group mb-4">
                                    <label class="col-md-12 p-0">Unit in stock</label>
                                    <div class="col-md-12 border-bottom p-0">
                                        <p>@Model.UnitInStock</p>
                                    </div>
                                </div>
                                <div class="form-group mb-4">
                                    <label class="col-md-12 p-0">Short Description</label>
                                    <div class="col-md-12 border-bottom p-0">
                                        <p>@Model.ShortDesc</p>
                                    </div>
                                </div>
                                <div class="form-group mb-4">
                                    <label class="col-md-12 p-0">Description</label>
                                    <div class="col-md-12 border-bottom p-0">
                                        <p>@Model.Description</p>
                                    </div>
                                </div>
                                <div class="form-group mb-4">
                                    <label class="col-md-12 p-0">Price</label>
                                    <div class="col-md-12 border-bottom p-0">
                                        <p>@Model.Price</p>
                                    </div>
                                </div>
                                <div class="form-group mb-4">
                                    <label class="col-md-12 p-0">Discount</label>
                                    <div class="col-md-12 border-bottom p-0">
                                        <p>@Model.Discount %</p>
                                    </div>
                                </div>
                                <div class="form-group mb-4">
                                    <label class="col-md-12 p-0">Category</label>
                                    <div class="col-md-12 border-bottom p-0">
                                        <p>
                                            @if (@Model.Cat == null)
                                            {
                                                <div class="d-flex align-items-center">
                                                    <div class="badge badge-success badge-dot m-r-10"></div>
                                                    <div>Unknow</div>
                                                </div>

                                            }
                                            else
                                            {
                                                <div class="d-flex align-items-center">
                                                    <div class="badge badge-success badge-dot m-r-10"></div>
                                                    <div>@Model.Cat.CatName</div>
                                                </div>

                                            }
                                        </p>
                                    </div>
                                </div>
                                <div class="form-group mb-4">
                                    <label class="col-md-12 p-0">Home flag</label>
                                    <div class="col-md-12 border-bottom p-0">
                                        <p>@Model.HomeFlag</p>
                                    </div>
                                </div>
                                <div class="form-group mb-4">
                                    <label class="col-md-12 p-0">Active</label>
                                    <div class="col-md-12 border-bottom p-0">
                                        <p>@Model.Active</p>
                                    </div>
                                </div>
                                <div class="form-group mb-4">
                                    <label class="col-md-12 p-0">Best sellers</label>
                                    <p>@Model.BestSellers</p>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
                <!-- Column -->
            </div>



            <form asp-action="Delete">
                <input type="hidden" asp-for="ProductId" />
                <input type="submit" value="Delete" class="btn btn-danger" /> |
                <a asp-action="Index">Back to List</a>
            </form>
        </div>
    </div>
</div>

Areas/Admin/Views/AdminProducts/Details.cshtml
@model PE.Models.Product

@{
    ViewData["Title"] = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h1>Details</h1>
<div class="page-header">
    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a asp-area="Admin" asp-controller="Home" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Home</a>
            <a asp-area="Admin" asp-controller="AdminProducts" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Product list</a>
            <span class="breadcrumb-item active">Details</span>
        </nav>
    </div>
</div>

<div class="row">
    <!-- Column -->
    <div class="col-lg-4 col-xlg-3 col-md-12">
        <div class="white-box">
            <div class="user-bg">
                <img width="max" height="max" alt="product" src="~/images/products/@Model.Thumb">
                
            </div>
            <div class="user-btm-box mt-5 d-md-flex">
                <div class="col-md-4 col-sm-4 text-center">
                    <h1>
                        @if(@Model.Thumb != null)
                        {
                            <p>@Model.Thumb</p>
                        }
                        else
                        {
                           <p>Unknown</p> 
                        }
                    </h1>
                </div>
            </div>
        </div>
    </div>
    <!-- Column -->
    <!-- Column -->
    <div class="col-lg-8 col-xlg-9 col-md-12">
        <div class="card">
            <div class="card-body">
                <div class="form-group mb-4">
                    <label class="col-md-12 p-0">Full Name</label>
                    <div class="col-md-12 border-bottom p-0">
                        <p>@Model.ProductName</p>
                    </div>
                    <div class="form-group mb-4">
                        <label class="col-md-12 p-0">Title</label>
                        <div class="col-md-12 border-bottom p-0">
                            <p>@Model.Title</p>
                        </div>
                    </div>
                    <div class="form-group mb-4">
                        <label class="col-md-12 p-0">Unit in stock</label>
                        <div class="col-md-12 border-bottom p-0">
                            <p>@Model.UnitInStock</p>
                        </div>
                    </div>
                    <div class="form-group mb-4">
                        <label class="col-md-12 p-0">Short Description</label>
                        <div class="col-md-12 border-bottom p-0">
                            <p>@Model.ShortDesc</p>
                        </div>
                    </div>
                    <div class="form-group mb-4">
                        <label class="col-md-12 p-0">Description</label>
                        <div class="col-md-12 border-bottom p-0">
                            <p>@Model.Description</p>
                        </div>
                    </div>
                    <div class="form-group mb-4">
                        <label class="col-md-12 p-0">Price</label>
                        <div class="col-md-12 border-bottom p-0">
                            <p>@Model.Price</p>
                        </div>
                    </div>
                    <div class="form-group mb-4">
                        <label class="col-md-12 p-0">Discount</label>
                        <div class="col-md-12 border-bottom p-0">
                            <p>@Model.Discount %</p>
                        </div>
                    </div>
                    <div class="form-group mb-4">
                        <label class="col-md-12 p-0">Category</label>
                        <div class="col-md-12 border-bottom p-0">
                            <p>
                                @if (@Model.Cat == null)
                                {
                                    <div class="d-flex align-items-center">
                                        <div class="badge badge-success badge-dot m-r-10"></div>
                                        <div>Unknow</div>
                                    </div>

                                }
                                else
                                {
                                    <div class="d-flex align-items-center">
                                        <div class="badge badge-success badge-dot m-r-10"></div>
                                        <div>@Model.Cat.CatName</div>
                                    </div>

                                }
                            </p>
                        </div>
                    </div>
                    <div class="form-group mb-4">
                        <label class="col-md-12 p-0">Home flag</label>
                        <div class="col-md-12 border-bottom p-0">
                            <p>@Model.HomeFlag</p>
                        </div>
                    </div>
                    <div class="form-group mb-4">
                        <label class="col-md-12 p-0">Active</label>
                        <div class="col-md-12 border-bottom p-0">
                            <p>@Model.Active</p>
                        </div>
                    </div>
                    <div class="form-group mb-4">
                        <label class="col-md-12 p-0">Best sellers</label>
                        <p>@Model.BestSellers</p>
                    </div>
                </div>

            </div>
        </div>
    </div>
    <!-- Column -->
</div>