Areas/Admin/Controllers/AdminPagesController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using AspNetCoreHero.ToastNotification.Abstractions;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PE.Helpers;
using PE.Models;
using PE.Models.paging;

namespace PE.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class AdminPagesController : Controller
    {
        private readonly shopPEContext _context;

        public INotyfService _notyfService { get; }

        public AdminPagesController(shopPEContext context, INotyfService notyfService)
        {
            _context = context;
            _notyfService = notyfService;
        }

        // GET: Admin/AdminPages
        public async Task<IActionResult> Index( string searchString, string currentFilter, int? pageNumber)
        {
            //for(int i = 0; i<20; i++)
            //{
            //    Page page = new Page();
            //    page.Title = "tin moi";
            //    page.PageName = "tin moi";
            //    page.Published = true;
            //    page.CreateDate = DateTime.Now;
            //    page.Contents = "tin moi tin moi tin moi";
            //    _context.Add(page);
            //    _context.SaveChanges();
            //}
            

            //paging
            if (searchString != null)
            {
                pageNumber = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewData["CurrentFilter"] = searchString;

            ////
            var pages = from s in _context.Pages
                           select s;

            //search
            //name
            if (!String.IsNullOrEmpty(searchString))
            {
                pages = pages.Where(p => p.PageName.Contains(searchString));
            }

         

            int pageSize = 5;

            //result
            return View(await PaginatedList<Page>.CreateAsync(pages.AsNoTracking(), pageNumber ?? 1, pageSize));

        }

        // GET: Admin/AdminPages/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var page = await _context.Pages
                .FirstOrDefaultAsync(m => m.PageId == id);
            if (page == null)
            {
                return NotFound();
            }

            return View(page);
        }

        // GET: Admin/AdminPages/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Admin/AdminPages/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("PageId,PageName,Contents,Thumb,Published,Title,MetaDesc,MetalKey,Alias,CreateDate,Ordering")] Page page, Microsoft.AspNetCore.Http.IFormFile fThumb)
        {
            if (ModelState.IsValid)
            {
                page.Title = Utilites.ToTitleCase(page.Title);
                if (fThumb != null)
                {
                    string extentions = Path.GetExtension(fThumb.FileName);
                    string image = Utilites.SEOUrl(page.PageName) + extentions;
                    page.Thumb = await Utilites.UploadFile(fThumb, @"pages", image.ToLower());
                }
                if (string.IsNullOrEmpty(page.Thumb)) page.Thumb = "default.jpg";
                page.Alias = Utilites.SEOUrl(page.PageName);
                page.CreateDate = DateTime.Now;

                _context.Add(page);
                _notyfService.Success("Success");
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(page);
        }

        // GET: Admin/AdminPages/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var page = await _context.Pages.FindAsync(id);
            if (page == null)
            {
                return NotFound();
            }
            return View(page);
        }

        // POST: Admin/AdminPages/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("PageId,PageName,Contents,Thumb,Published,Title,MetaDesc,MetalKey,Alias,CreateDate,Ordering")] Page page, Microsoft.AspNetCore.Http.IFormFile fThumb)
        {
            if (id != page.PageId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    page.Title = Utilites.ToTitleCase(page.Title);
                    if (fThumb != null)
                    {
                        string extentions = Path.GetExtension(fThumb.FileName);
                        string image = Utilites.SEOUrl(page.PageName) + extentions;
                        page.Thumb = await Utilites.UploadFile(fThumb, @"pages", image.ToLower());
                    }
                    if (string.IsNullOrEmpty(page.Thumb)) page.Thumb = "default.jpg";
                    page.Alias = Utilites.SEOUrl(page.PageName);
                    page.CreateDate = DateTime.Now;

                    _context.Update(page);
                    _notyfService.Success("Success");
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PageExists(page.PageId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(page);
        }

        // GET: Admin/AdminPages/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var page = await _context.Pages
                .FirstOrDefaultAsync(m => m.PageId == id);
            if (page == null)
            {
                return NotFound();
            }

            return View(page);
        }

        // POST: Admin/AdminPages/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var page = await _context.Pages.FindAsync(id);
            _context.Pages.Remove(page);
            _notyfService.Success("Success");
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PageExists(int id)
        {
            return _context.Pages.Any(e => e.PageId == id);
        }
    }
}

Areas/Admin/Views/AdminPages/Create.cshtml
@model PE.Models.Page

@{
    ViewData["Title"] = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<head>
    <!-- Favicon -->
    <link rel="shortcut icon" href="~/Admin/assets/images/logo/favicon.png">

    <!-- page css -->
    <link href="~/Admin/assets/vendors/select2/select2.css" rel="stylesheet">

    <!-- Core css -->
    <link href="~/Admin/assets/css/app.min.css" rel="stylesheet">
</head>

<h1>Create</h1>
<div class="page-header">
    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a asp-area="Admin" asp-controller="Home" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Home</a>
            <a asp-area="Admin" asp-controller="AdminPages" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Page list</a>
            <span class="breadcrumb-item active">Create</span>
        </nav>
    </div>
</div>

<h4>Page</h4>
<hr />
<form asp-controller="AdminPages" asp-action="Create" method="post" enctype="multipart/form-data">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="page-header no-gutters has-tab">
        <div class="d-md-flex m-b-15 align-items-center justify-content-between">
            <div class="media align-items-center m-b-15">
            </div>
            <div class="m-b-15">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </div>
        <ul class="nav nav-tabs">
            <li class="nav-item">
                <a class="nav-link active" data-toggle="tab" href="#product-edit-basic">Basic Info</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" data-toggle="tab" href="#product-edit-option">Option Info</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" data-toggle="tab" href="#product-edit-description">Description</a>
            </li>
        </ul>
    </div>
    <div class="tab-content m-t-15">
        <div class="tab-pane fade show active" id="product-edit-basic">
            <div class="card">
                <div class="card-body">
                    <div class="row">
                        <div class="form-group col-md-9">
                            <label class="font-weight-semibold" asp-for="PageName">Page Name</label>
                            <input asp-for="PageName" class="form-control" />
                            <span asp-validation-for="PageName" class="text-danger"></span>
                        </div>
                        <div class="form-group  col-md-3">
                            <label class="font-weight-semibold" asp-for="Title">Title</label>
                            <input asp-for="Title" class="form-control" />
                            <span asp-validation-for="Title" class="text-danger"></span>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="font-weight-semibold" asp-for="Thumb">Thumbnail</label>
                        <input name="fThumb" asp-for="Thumb" type="file" class="form-control-file" />
                    </div>
                    <div class="row">
                        <div class="m-t-25">
                            <div class="form-group d-flex align-items-center">
                                <div class="switch m-r-10">
                                    <input type="checkbox" asp-for="Published" />
                                    <label for="Published"></label>
                                </div>
                                <label>Published</label>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="tab-pane fade" id="product-edit-option">
                <div class="card">
                    <div class="card-body">
                        <div class="form-group">
                            <label class="font-weight-semibold" asp-for="MetaDesc">MetaDesc</label>
                            <input asp-for="MetaDesc" class="form-control" />
                            <span asp-validation-for="MetaDesc" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label class="font-weight-semibold" asp-for="MetalKey">MetalKey</label>
                            <input asp-for="MetalKey" class="form-control" />
                            <span asp-validation-for="MetalKey" class="text-danger"></span>
                        </div>

                    </div>
                </div>
            </div>
            <div class="tab-pane fade" id="product-edit-description">
                <div class="card">
                    <div class="card-body">
                        <div id="productDescription">
                            <label class="font-weight-semibold" asp-for="Contents">Content</label>
                            <input asp-for="Contents" class="form-control" />
                            <span asp-validation-for="Contents" class="text-danger"></span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
</form>


<!-- Core Vendors JS -->
<script src="~/Admin/assets/js/vendors.min.js"></script>

@section Scripts{
    <script>
        new Quill('#productDescription', {
            theme: 'snow'
        })
    </script>

    <script src="~/Admin/assets/vendors/select2/select2.min.js"></script>
    <script src="~/Admin/assets/vendors/quill/quill.min.js"></script>
    <script src="~/Admin/assets/js/pages/e-commerce-product-edit.js"></script>

}
    <!-- page js -->
    <!-- Core JS -->
    <script src="~/Admin/assets/js/app.min.js"></script>

Areas/Admin/Views/AdminPages/Delete.cshtml
@model PE.Models.Page

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h1>Delete</h1>
<div class="page-header">
    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a asp-area="Admin" asp-controller="Home" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Home</a>
            <a asp-area="Admin" asp-controller="AdminPages" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Page list</a>
            <span class="breadcrumb-item active">Delete</span>
        </nav>
    </div>
</div>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Page</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PageName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PageName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Contents)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Contents)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Thumb)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Thumb)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Published)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Published)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MetaDesc)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MetaDesc)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MetalKey)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MetalKey)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Alias)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Alias)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreateDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreateDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Ordering)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Ordering)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="PageId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Areas/Admin/Views/AdminPages/Details.cshtml
@model PE.Models.Page

@{
    ViewData["Title"] = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}
<head>
    <!-- Favicon -->
    <link rel="shortcut icon" href="~/Admin/assets/images/logo/favicon.png">

    <!-- page css -->
    <!-- Core css -->
    <link href="~/Admin/assets/css/app.min.css" rel="stylesheet">

</head>

<h1>Details</h1>
<div class="page-header">
    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a asp-area="Admin" asp-controller="Home" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Home</a>
            <a asp-area="Admin" asp-controller="AdminPages" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Page list</a>
            <span class="breadcrumb-item active">Details</span>
        </nav>
    </div>
</div>

<div>
    <div class="main-content">
        <div class="card">
            <div class="card-body">
                <div class="container">
                    <h2 class="font-weight-normal m-b-10">@Model.Title</h2>
                    <div class="d-flex m-b-30">
                        <div class="avatar avatar-cyan avatar-img">

                        </div>
                        <div class="m-l-15">
                            <p class="m-b-0 text-muted font-size-13">@Model.CreateDate</p>
                        </div>
                    </div>
                    <img alt="Thumbnail" class="img-fluid w-100" src="~/images/pages/@Model.Thumb">
                    <div class="m-t-30">
                        <p>@Model.Contents</p>
                    </div>
                    <div class="d-flex m-t-40 align-items-center">
                        <span class="m-r-15">Share this post: </span>
                        <ul class="list-inline m-b-0">
                            <li class="list-inline-item">
                                <button class="font-size-16 btn btn-hover btn-icon btn-rounded">
                                    <i class="anticon anticon-facebook"></i>
                                </button>
                            </li>
                            <li class="list-inline-item">
                                <button class="font-size-16 btn btn-hover btn-icon btn-rounded">
                                    <i class="anticon anticon-twitter"></i>
                                </button>
                            </li>
                            <li class="list-inline-item">
                                <button class="font-size-16 btn btn-hover btn-icon btn-rounded">
                                    <i class="anticon anticon-instagram"></i>
                                </button>
                            </li>
                        </ul>
                    </div>
                    <hr>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Core Vendors JS -->
<script src="~/Admin/assets/js/vendors.min.js"></script>

<!-- page js -->
<!-- Core JS -->
<script src="~/Admin/assets/js/app.min.js"></script>

Areas/Admin/Views/AdminPages/Edit.cshtml
@model PE.Models.Page

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<head>
    <!-- Favicon -->
    <link rel="shortcut icon" href="~/Admin/assets/images/logo/favicon.png">

    <!-- page css -->
    <link href="~/Admin/assets/vendors/select2/select2.css" rel="stylesheet">

    <!-- Core css -->
    <link href="~/Admin/assets/css/app.min.css" rel="stylesheet">
</head>

<h1>Edit: @Model.Title</h1>
<div class="page-header">
    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a asp-area="Admin" asp-controller="Home" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Home</a>
            <a asp-area="Admin" asp-controller="AdminPages" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Page list</a>
            <span class="breadcrumb-item active">Edit: @Model.Title</span>
        </nav>
    </div>
</div>

<h4>Page</h4>
<hr />
<form asp-controller="AdminPages" asp-action="Edit" asp-route-id="@Model.PageId" method="post" enctype="multipart/form-data">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <input type="hidden" asp-for="PageId" />
    <input type="hidden" asp-for="CreateDate" />
    <input type="hidden" asp-for="Thumb" />
    <div class="page-header no-gutters has-tab">
        <div class="d-md-flex m-b-15 align-items-center justify-content-between">
            <div class="media align-items-center m-b-15">
            </div>
            <div class="m-b-15">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </div>
        <ul class="nav nav-tabs">
            <li class="nav-item">
                <a class="nav-link active" data-toggle="tab" href="#product-edit-basic">Basic Info</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" data-toggle="tab" href="#product-edit-option">Option Info</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" data-toggle="tab" href="#product-edit-description">Description</a>
            </li>
        </ul>
    </div>
    <div class="tab-content m-t-15">
        <div class="tab-pane fade show active" id="product-edit-basic">
            <div class="card">
                <div class="card-body">
                    <div class="row">
                        <div class="form-group col-md-9">
                            <label class="font-weight-semibold" asp-for="PageName">Page Name</label>
                            <input asp-for="PageName" class="form-control" />
                            <span asp-validation-for="PageName" class="text-danger"></span>
                        </div>
                        <div class="form-group  col-md-3">
                            <label class="font-weight-semibold" asp-for="Title">Title</label>
                            <input asp-for="Title" class="form-control" />
                            <span asp-validation-for="Title" class="text-danger"></span>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <label class="font-weight-semibold" asp-for="Thumb">Thumbnail</label>
                    <input name="fThumb" asp-for="Thumb" type="file" class="form-control-file" />
                </div>
                <div class="row">
                    <div class="m-t-25">
                        <div class="form-group d-flex align-items-center">
                            <div class="switch m-r-10">
                                <input type="checkbox" asp-for="Published" />
                                <label for="Published"></label>
                            </div>
                            <label>Published</label>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="tab-pane fade" id="product-edit-option">
            <div class="card">
                <div class="card-body">
                    <div class="form-group">
                        <label class="font-weight-semibold" asp-for="MetaDesc">MetaDesc</label>
                        <input asp-for="MetaDesc" class="form-control" />
                        <span asp-validation-for="MetaDesc" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label class="font-weight-semibold" asp-for="MetalKey">MetalKey</label>
                        <input asp-for="MetalKey" class="form-control" />
                        <span asp-validation-for="MetalKey" class="text-danger"></span>
                    </div>

                </div>
            </div>
        </div>
        <div class="tab-pane fade" id="product-edit-description">
            <div class="card">
                @*<div class="card-body">
                    <div id="productDescription">
                        <label class="font-weight-semibold" asp-for="Contents">Content</label>
                        <input asp-for="Contents" class="form-control" />
                    </div>
                </div>*@
                <div class="form-group">
                        <label class="font-weight-semibold" asp-for="Contents">Contents</label>
                        <input asp-for="Contents" class="form-control" />
                        <span asp-validation-for="Contents" class="text-danger"></span>
                    </div>
            </div>
        </div>
    </div>
</form>


<!-- Core Vendors JS -->
<script src="~/Admin/assets/js/vendors.min.js"></script>

@section Scripts{
    <script>
        new Quill('#productDescription', {
            theme: 'snow'
        })
    </script>

    <script src="~/Admin/assets/vendors/select2/select2.min.js"></script>
    <script src="~/Admin/assets/vendors/quill/quill.min.js"></script>
    <script src="~/Admin/assets/js/pages/e-commerce-product-edit.js"></script>

}
    <!-- page js -->
    <!-- Core JS -->
    <script src="~/Admin/assets/js/app.min.js"></script>

Areas/Admin/Views/AdminPages/Index.cshtml
@model PE.Models.paging.PaginatedList<PE.Models.Page>

@{
    ViewData["Title"] = "Pages";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h1>Page list</h1>

<div class="page-header">
    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a asp-area="Admin" asp-controller="Home" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Home</a>
            <span class="breadcrumb-item active">Page list page: @Model.PageIndex</span>
        </nav>
    </div>
</div>

<!--search-->
<div style="display: flex; justify-content: space-between;">
    <!--search category-->
    <form asp-action="Index" method="get">
        <div class="form-actions no-color">
            <p>
                Find by name: <input type="text" name="SearchString" value="@ViewData["CurrentFilter"]" />
                <input type="submit" value="Search" class="btn btn-primary" /> |
                <a asp-action="Index">Back to Full List</a>
            </p>
        </div>
    </form>
</div>



<div class="row">
    <div class="col-sm-12">
        <div class="white-box">
            <div style="display: flex; justify-content: space-between;">
                <h3 class="box-title">Pages Table</h3>
                <a class="btn btn-info" asp-action="Create">Create new</a>
            </div>
            <div class="table-responsive">
                <table class="table text-nowrap">
                    <thead>
                        <tr>
                            <th class="border-top-0">ID</th>
                            <th class="border-top-0">Name</th>
                            <th class="border-top-0">Status</th>
                            <th class="border-top-0">#</th>

                        </tr>
                    </thead>
                    <tbody>
                        @if (Model != null)
                        {
                            foreach (var item in Model)
                            {
                                <tr>
                                    <td scope="row">@item.PageId</td>
                                    <td>@item.PageName</td>
                                    <td>
                                        @if (@item.Published == true)
                                        {
                                            <div class="d-flex align-items-center">
                                                <div class="badge badge-success badge-dot m-r-10"></div>
                                                <div>Pubished</div>
                                            </div>

                                        }
                                        else
                                        {
                                            <div class="d-flex align-items-center">
                                                <div class="badge badge-success badge-dot m-r-10"></div>
                                                <div>Non-published</div>
                                            </div>
                                        }
                                    </td>

                                    <td>
                                        <a class="btn btn-primary btn-tone m-r-5"
                                   asp-area="Admin" asp-controller="AdminPages" asp-action="Details" asp-route-id="@item.PageId">View</a>
                                        <a class="btn btn-secondary btn-tone m-r-5"
                                   asp-area="Admin" asp-controller="AdminPages" asp-action="Edit" asp-route-id="@item.PageId">Edit</a>
                                        <a class="btn btn-success btn-tone m-r-5"
                                   asp-area="Admin" asp-controller="AdminPages" asp-action="Delete" asp-route-id="@item.PageId">Delete</a>
                                    </td>
                                </tr>
                            }
                        }
                    </tbody>
                </table>
                @{
                    var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
                    var nextDisabled = !Model.HasNextPage ? "disabled" : "";
                }

                <a asp-action="Index"
                   asp-route-sortOrder="@ViewData["CurrentSort"]"
                   asp-route-pageNumber="@(Model.PageIndex - 1)"
                   asp-route-currentFilter="@ViewData["CurrentFilter"]"
                   class="btn btn-facebook @prevDisabled">
                    Previous
                </a>
                <a asp-action="Index"
                   asp-route-sortOrder="@ViewData["CurrentSort"]"
                   asp-route-pageNumber="@(Model.PageIndex + 1)"
                   asp-route-currentFilter="@ViewData["CurrentFilter"]"
                   class="btn btn-danger @nextDisabled">
                    Next
                </a>
            </div>
        </div>
    </div>
</div>